config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppage#index"
  resources :toppage do
    collection do
      get "search"
    end
  end

  resources :brands
  resources :users, except: :show do 
    member do
      get 'profile'
      patch 'profile_update'
      get 'address_edit'
      patch 'address_update'
      get 'payment'
      get 'email'
      get 'identification'
      get 'phone'
    end
  end

  resources :users, only: :show do
    member do
      get 'logout'
      get 'notification'
      get 'news'
      get 'guide'
      get 'contact'
      get 'todo'
      get 'likes'
      get 'items'
      get 'dealing'
      get 'sold'
      get 'buying'
      get 'bought'
      get 'rates'
    end
  end
  resources :brands
  resources :categories, only: [:index, :show]
  resources :goods,  except: [:index] do
    resources :buys,  only: [:index, :create]
    member do
      get 'selledit'
    end
  end

  resources :credit, only: [:new, :show] do
    collection do
      post 'show', to: 'credits#show'
      post 'pay', to: 'credits#pay'
      post 'delete', to: 'credits#delete'
    end
  end
  
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      get 'done'
    end
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  
  require "payjp"
  
  def step1
    #新規インスタンス作成
    @user = User.new
  end

  def step2
    
    session[:nick_name] = user_params[:nick_name]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:family_name] = user_params[:family_name]
    session[:first_name] = user_params[:first_name]
    session[:family_kana] = user_params[:family_kana]
    session[:first_kana] = user_params[:first_kana]
    session[:birthday_year] = user_params[:birthday_year]
    session[:birthday_month] = user_params[:birthday_month]
    session[:birthday_date] = user_params[:birthday_date]
    @user = User.new
  end

  def step3
    session[:phone_number] = user_params[:phone_number]
    
    @user = User.new
    @address = Address.new
  end

  def step4
    @user = User.create(
      nick_name: session[:nick_name],
      email: session[:email],
      password: session[:password],
      family_name: session[:family_name],
      first_name: session[:first_name],
      family_kana: session[:family_kana],
      first_kana: session[:first_kana],
      birthday_year: session[:birthday_year],
      birthday_month: session[:birthday_month],
      birthday_date: session[:birthday_date],
      phone_number: session[:phone_number]
    )
    if @user.save
      @address = Address.create( 
        family_name: address_params[:family_name],
        first_name: address_params[:first_name],
        family_kana: address_params[:family_kana],
        first_kana: address_params[:first_kana],
        post: address_params[:post],
        prefecture: address_params[:prefecture],
        city: address_params[:city],
        address: address_params[:address],
        buil: address_params[:buil],
        phone_number: address_params[:phone_number],
        user_id: @user.id
      )
      unless @address.save
        redirect_to step3_signup_index_path
        flash.now[:alert] = '登録情報の記入に間違いがある可能性があります'
      end
      sign_in User.find(@user.id) 
    else

      flash.now[:alert] = '登録情報の記入に間違いがある可能性があります'
      redirect_to step1_signup_index_path
    end
  end
  
  def done
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to step4_signup_index_path
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token']
      )
      @card = Credit.create(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
      else
        redirect_to step4_signup_index_path
        flash[:alert] = 'クレジットカード登録に失敗しました'
      end
    end
  end

  def create
    
  end

  private

  def user_params
    params.require(:user).permit(
      :nick_name,
      :email,
      :password,
      :family_name,
      :first_name,
      :family_kana,
      :first_kana,
      :birthday_year,
      :birthday_month,
      :birthday_date,
      :phone_number
    )
  end

  def address_params
    params.require(:address).permit(
      :family_name,
      :first_name,
      :family_kana,
      :first_kana,
      :phone_number,
      :post,
      :prefecture,
      :city,
      :address,
      :buil,
      :phone_number
    )
  end

end

app/views/signup/done.html.haml
.single_header2
  %h1.single_header2__link
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg",  size: "185x49", alt: "Mercari", class: "single_header2__link__img"
  .new-nav
    %ol
      %li
        会員情報
      %li.phone
        電話番号認証
      %li.adress
        お届け先住所入力
      %li.pay
        支払い方法
      %li
        完了
    %ul
      %li
        ●
      %li
        ●
      %li
        ●
      %li
        ●
      %li
        ●
.pay-box.done-box
  .pay-box__container
    .pay-box__container__text
      会員登録完了
    .done-message
      ありがとうございます。
      %br
      会員登録が完了しました。
    = link_to root_path do
      .start-mercari
        メルカリをはじめる
.footer-new
  .footer-text
    %ul
      %li 
        プライバシーポリシー
      %li 
        メルカリ利用規約
      %li 
        特定商取引に関する規約   
  .footer-rogo
    = image_tag "show.png",  size: "80x65"
  .footer-lnc
    ©︎Mercari,lnc.

app/views/signup/step1.html.haml
.single_header2
  %h1.single_header2__link
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg",  size: "185x49", alt: "Mercari", class: "single_header2__link__img"
  .new-nav
    %ol
      %li
        会員情報
      %li.phone
        電話番号認証
      %li.adress
        お届け先住所入力
      %li.pay
        支払い方法
      %li
        完了
    %ul
      %li
        ●
      %li
        ●
      %li
        ●
      %li
        ●
      %li
        ●
.user-new
  .user-new__main
    .user-new__main__text
      会員情報入力
    .user-new__main__form
      .user-new__main__form__content
        = form_for @user, url: step2_signup_index_path, method: :get, html: {class: 'first-main__box'} do |f|
          .user-new__main__form__content__text
            %h ニックネーム
            .red2 必須
          = f.text_field :nick_name, placeholder: '例) メルカリ太郎',class: "user-new__main__form__content__text__nickname"
          .user-new__main__form__content__text.item
            %h メールアドレス
            .red2 必須
          = f.email_field :email, placeholder: 'PC・携帯どちらでも可',class: "user-new__main__form__content__text__nickname"
          .password-form
            .user-new__main__form__content__text.item
              %h パスワード
              .red2 必須
            = f.password_field :password, placeholder: 'パスワード6文字以上',class: "user-new__main__form__content__text__nickname"
            .caution-text
              ※英字と数字の両方を含めて設定してください
            -# = f.check_box :password
            -# %label.check-text
            -#   パスワードを表示する
          .current-user
            .current-user__text
              本人確認
            .current-user__main
              安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
          .user-name
            .user-new__main__form__content__text
              %h お名前 (全角)
              .red2 必須
            .user-name__kanji
              = f.text_field :family_name, placeholder:"例）山田"
              = f.text_field :first_name, placeholder:"例）彩"
          .user-kana
            .user-new__main__form__content__text
              %h お名前カナ (全角)
              .red2 必須
            = f.text_field :family_kana, placeholder:"例）ヤマダ"
            = f.text_field :first_kana, placeholder:"例）アヤ"
          .birthday
            .user-new__main__form__content__text
              %h 生年月日
              .red2 必須
            = f.select :birthday_year,[["2019","2019"],["2018","2018"]],{ prompt: '--' }
            %label
              年
            = f.select :birthday_month,[["12","12"],["11","11"]],{ prompt: '--' }
            %label
              月
            = f.select :birthday_date,[["31","31"],["30","30"]],{ prompt: '--' }
            %label
              日
            .birthday__caution
              生年月日を入力してください
          .user-caution
            ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
          .step1-next
            .step1-next__text
              「次へ進む」のボタンを押すことにより、利用規約に同意したものとみなします
            = f.submit '次へ進む',class:'step1-next__btn'
            .about-register
              本人情報の登録について＞
            .english
              This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.
.footer-new
  .footer-text
    %ul
      %li 
        プライバシーポリシー
      %li 
        メルカリ利用規約
      %li 
        特定商取引に関する規約   
  .footer-rogo
    = image_tag "show.png",  size: "80x65"
  .footer-lnc
    ©︎Mercari,lnc.

app/views/signup/step2.html.haml
.single_header2
  %h1.single_header2__link
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg",  size: "185x49", alt: "Mercari", class: "single_header2__link__img"
  .new-nav
    %ol
      %li
        会員情報
      %li.phone
        電話番号認証
      %li.adress
        お届け先住所入力
      %li.pay
        支払い方法
      %li
        完了
    %ul
      %li
        ●
      %li
        ●
      %li
        ●
      %li
        ●
      %li
        ●
.number-confirm
  .number-confirm__container
    .number-confirm__container__text
      電話番号の確認
    = form_for @user, url: step3_signup_index_path, method: :get, html: {class: 'second-main__box'} do |f|
      .number-form-box
        .number-form-box__container
          %label 電話番号の確認
          = f.text_field :phone_number, placeholder:'携帯電話の番号を入力'
          .number-form-box__container__text
            本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
          = f.submit 'SMSを送信する' ,class: 'sms-btn'
          .number-form-box__container__caution
            ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
          .confirm-reason
            電話番号の確認が必要な理由＞
.footer-new
  .footer-text
    %ul
      %li 
        プライバシーポリシー
      %li 
        メルカリ利用規約
      %li 
        特定商取引に関する規約   
  .footer-rogo
    = image_tag "show.png",  size: "80x65"
  .footer-lnc
    ©︎Mercari,lnc.

app/views/signup/step3.html.haml
.single_header2
  %h1.single_header2__link
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg",  size: "185x49", alt: "Mercari", class: "single_header2__link__img"
  .new-nav
    %ol
      %li
        会員情報
      %li.phone
        電話番号認証
      %li.adress
        お届け先住所入力
      %li.pay
        支払い方法
      %li
        完了
    %ul
      %li
        ●
      %li
        ●
      %li
        ●
      %li
        ●
      %li
        ●
.address-box
  .address-box__container
    .address-box__container__text
      住所入力
    = form_for @address, url: step4_signup_index_path, method: :get, html: {class: 'third-main__box'} do |f|
      .user-new__main__form__content__text
        %h お名前
        .red2 必須
      = f.text_field :family_name, placeholder:"例）山田"
      = f.text_field :first_name, placeholder:"例）彩"
      .user-new__main__form__content__text
        %h お名前カナ
        .red2 必須
      = f.text_field :family_kana, placeholder:"例）ヤマダ"
      = f.text_field :first_kana, placeholder:"例）アヤ"
      .user-new__main__form__content__text
        %h 郵便番号
        .red2 必須
      = f.text_field :post, placeholder:"例）123-4567"
      .user-new__main__form__content__text
        %h 都道府県
        .red2 必須
      = f.collection_select :prefecture, Area.all,:id,:name,{prompt:'---'}
      .user-new__main__form__content__text
        %h 市区町村
        .red2 必須
      = f.text_field :city, placeholder:"例）横浜市緑区"
      .user-new__main__form__content__text
        %h 番地
        .red2 必須
      = f.text_field :address, placeholder:"例）青山1-1-1"
      .user-new__main__form__content__text
        %h 建物名
        .gray2 任意
      = f.text_field :buil, placeholder: "例）柳ビル103"
      .user-new__main__form__content__text
        %h 電話
        .gray2 任意
      = f.text_field :phone_number, placeholder: "例) 09012345678"
      = f.submit "次へ進む",class:"address-next"
.footer-new
  .footer-text
    %ul
      %li 
        プライバシーポリシー
      %li 
        メルカリ利用規約
      %li 
        特定商取引に関する規約   
  .footer-rogo
    = image_tag "show.png",  size: "80x65"
  .footer-lnc
    ©︎Mercari,lnc.

app/views/signup/step4.html.haml
.single_header2
  %h1.single_header2__link
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg",  size: "185x49", alt: "Mercari", class: "single_header2__link__img"
  .new-nav
    %ol
      %li
        会員情報
      %li.phone
        電話番号認証
      %li.adress
        お届け先住所入力
      %li.pay
        支払い方法
      %li
        完了
    %ul
      %li
        ●
      %li
        ●
      %li
        ●
      %li
        ●
      %li
        ●
.pay-box
  .pay-box__container
    .pay-box__container__text
      支払い方法
    = form_tag(done_signup_index_path, method: :get, id: 'charge-form',  name: "inputForm") do
      %label カード番号
      %li 必須
      = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
      %br
      .crad--type
        %img
          = image_tag asset_path("visa.png"), size:'49x20'
        %img
          = image_tag asset_path("mastercard.png"), size:'30x20'
        %img
          = image_tag asset_path("saison.png"), size:'30x20'
        %img
          = image_tag asset_path("jcb.png"), size:'30x20'
        %img
          = image_tag asset_path("amex.png"), size:'30x20'
        %img
          = image_tag asset_path("diners.png"), size:'30x20'
        %img
          = image_tag asset_path("discover.png"), size:'30x20'
      .crad--deadline   
        %label 有効期限
        %li 必須
        %select#exp_month{name: "exp_month", type: "text"}
          %option{value: ""} --
          %option{value: "1"}01
          %option{value: "2"}02
          %option{value: "3"}03
          %option{value: "4"}04
          %option{value: "5"}05
          %option{value: "6"}06
          %option{value: "7"}07
          %option{value: "8"}08
          %option{value: "9"}09
          %option{value: "10"}10
          %option{value: "11"}11
          %option{value: "12"}12
        %span 月/
        %select#exp_year{name: "exp_year", type: "text"}
          %option{value: ""} --
          %option{value: "2019"}19
          %option{value: "2020"}20
          %option{value: "2021"}21
          %option{value: "2022"}22
          %option{value: "2023"}23
          %option{value: "2024"}24
          %option{value: "2025"}25
          %option{value: "2026"}26
          %option{value: "2027"}27
          %option{value: "2028"}28
          %option{value: "2029"}29
        %span 年
        %br
      .crad--code
      %label セキュリティコード
      %ul 必須
      = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
      .code
        カードの裏面の番号とは?
      #card_token
      = submit_tag "追加する", id: "token_submit"


.footer-new
  .footer-text
    %ul
      %li 
        プライバシーポリシー
      %li 
        メルカリ利用規約
      %li 
        特定商取引に関する規約   
  .footer-rogo
    = image_tag "show.png",  size: "80x65"
  .footer-lnc
    ©︎Mercari,lnc.