config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppage#index"
  resources :toppage do
    collection do
      get "search"
    end
  end

  resources :brands
  resources :users, except: :show do 
    member do
      get 'profile'
      patch 'profile_update'
      get 'address_edit'
      patch 'address_update'
      get 'payment'
      get 'email'
      get 'identification'
      get 'phone'
    end
  end

  resources :users, only: :show do
    member do
      get 'logout'
      get 'notification'
      get 'news'
      get 'guide'
      get 'contact'
      get 'todo'
      get 'likes'
      get 'items'
      get 'dealing'
      get 'sold'
      get 'buying'
      get 'bought'
      get 'rates'
    end
  end
  resources :brands
  resources :categories, only: [:index, :show]
  resources :goods,  except: [:index] do
    resources :buys,  only: [:index, :create]
    member do
      get 'selledit'
    end
  end

  resources :credit, only: [:new, :show] do
    collection do
      post 'show', to: 'credits#show'
      post 'pay', to: 'credits#pay'
      post 'delete', to: 'credits#delete'
    end
  end
  
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      get 'done'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :goods, dependent: :destroy
  has_many :buys
  has_many :credits
  has_one :address
  has_many :sns_credentials, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  validates :family_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/ }
  validates :first_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/ }
  validates :family_name, presence: true, format: { with: /\A[一-龥ぁ-ん]/ }
  validates :first_name, presence: true, format: { with: /\A[一-龥ぁ-ん]/ }
  
  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

      if user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else
        user = User.new(
          nick_name: auth.info.name,
          email: auth.info.email,
        )
        sns = SnsCredential.new(
          uid: auth.uid,
          provider: auth.provider
        )
      end
      return { user: user ,sns: sns}
    end

   def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    unless user.present?
      user = User.new(
        nickname: auth.info.name,
        email: auth.info.email,
      )
    end
    return {user: user}
   end

   def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    return { user: user ,sns: sns}
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end


  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else 
      @sns = info[:sns]
      render template: "devise/registrations/new" 
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  def new
    super
  end

  def create
    super
  end

  def edit
    super
  end

  def update
    super
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def new
    super
  end

  def create
    super
  end

  def edit
    super
  end

  def update
    super
  end

  def destroy
    super
  end 

  def cancel
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  def new
    super
  end
 
  def create
    super
  end
 
  def destroy
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_toppage

  def show
    @user = User.find(params[:id])
  end

  def profile
    @user = User.find_by(id: current_user.id)
  end

  def profile_update
    user = User.where(id: current_user.id)
    user.update(user_params)
    redirect_to user_path(current_user.id)
  end

  def address_edit
    @address = Address.find_by(user_id: current_user.id)
  end
  
  def address_update
    address = Address.where(user_id: current_user.id)[0]
    address.update(user_address_params)
    redirect_to user_path(current_user.id)
  end

  def payment
  end

  def email
    @user = User.find_by(id: current_user.id)
  end

  def identification
    @user = User.find(current_user.id)
  end

  def logout
  end

  def news
  end

  def guide
  end

  def contact
  end
 
  def todo
    @user = User.find_by(id: current_user.id)
  end

  def likes
    @user = User.find_by(id: current_user.id)
  end

  def items
    @goods = Good.where(user_id: current_user.id)
  end

  def dealing
    @goods = Good.where(user_id: current_user.id)
  end

  def sold
    @goods = Good.where(user_id: current_user.id)
  end

  def buying
    @buys = Buy.where(user_id: current_user.id)
    @good = []
    @buys.each do |buy|
      buy = Good.where(id: buy.good_id).first
      @good << buy
    end
  end

  def bought
    @buys = Buy.where(user_id: current_user.id)
    @good = []
    @buys.each do |buy|
      buy = Good.where(id: buy.good_id).first
      @good << buy
    end
  end

  def rates
    @user = User.find_by(id: current_user.id)
  end

  def edit
    @user = User.find_by(id: current_user.id)
  end
  
  private
  def user_address_params
    params.require(:address).permit(
      :family_name,
      :first_name,
      :family_kana,
      :first_kana,
      :phone_number,
      :post,
      :prefecture,
      :city,
      :address,
      :buil
    )
  end

  def user_params
    params.require(:user).permit(
      :nick_name,
      :email,
      :password,
      :family_name,
      :first_name,
      :family_kana,
      :first_kana,
      :birthday_year,
      :birthday_month,
      :birthday_date,
      :phone_number,
      :profile
    )
  end

  def move_to_toppage
    redirect_to root_path unless user_signed_in?
  end

end

app/views/users/_user_pankz.html.haml
.header-user-nav
  .header-user-nav__pankz
    %span
      = link_to "フリマケ", root_path
      %i.fas.fa-angle-right
    - if current_page?(user_path)
      %span.last-pankz マイページ
    - else
      = link_to user_path(current_user.id) do
        %span マイページ
      %i.fas.fa-angle-right
    - if current_page?(profile_user_path)
      %span.last-pankz プロフィール
    - if current_page?(address_edit_user_path)
      %span.last-pankz 発送先・お届け先住所変更
    - if current_page?(payment_user_path)
      %span.last-pankz 支払い方法
    - if current_page?(email_user_path)
      %span.last-pankz メール/パスワード
    - if current_page?(identification_user_path)
      %span.last-pankz 本人情報の登録
    - if current_page?(phone_user_path)
      %span.last-pankz 電話番号の確認
    - if current_page?(notification_user_path)
      %span.last-pankz お知らせ
    - if current_page?(todo_user_path)
      %span.last-pankz やることリスト
    - if current_page?(likes_user_path)
      %span.last-pankz いいね！一覧
    - if current_page?(items_user_path)
      %span.last-pankz 出品した商品 - 出品中
    - if current_page?(dealing_user_path)
      %span.last-pankz 出品した商品 - 取引中
    - if current_page?(sold_user_path)
      %span.last-pankz 出品した商品 - 売却済み
    - if current_page?(buying_user_path)
      %span.last-pankz 購入した商品 - 取引中
    - if current_page?(bought_user_path)
      %span.last-pankz 購入した商品 - 過去の取引
    - if current_page?(news_user_path)
      %span.last-pankz ニュース一覧
    - if current_page?(rates_user_path)
      %span.last-pankz 評価一覧
    - if current_page?(contact_user_path)
      %span.last-pankz お問い合わせ
    - if current_page?(logout_user_path)
      %span.last-pankz ログアウト

app/views/users/bought.html.haml
= render 'toppage/header'
= render "toppage/button"
= render "user_pankz"


.user-main
  .myside
    %nav.myside--top
      = link_to user_path(current_user.id), class: "myside--top__list" do
        %span マイページ
        %i.fas.fa-chevron-right
      = link_to notification_user_path(current_user.id), class: "myside--top__list" do
        %span お知らせ
        %i.fas.fa-chevron-right
      = link_to todo_user_path(current_user.id), class: "myside--top__list" do
        %span やることリスト
        %i.fas.fa-chevron-right
      = link_to likes_user_path(current_user.id), class: "myside--top__list" do
        %span いいね！一覧
        %i.fas.fa-chevron-right
      = link_to new_good_path, class: 'myside--top__list' do
        %span 出品する
        %i.fas.fa-chevron-right
      = link_to items_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 出品中
        %i.fas.fa-chevron-right
      = link_to dealing_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 取引中
        %i.fas.fa-chevron-right
      = link_to sold_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 売却済み
        %i.fas.fa-chevron-right
      = link_to buying_user_path(current_user.id), class: "myside--top__list" do
        %span 購入した商品 取引中
        %i.fas.fa-chevron-right
      = link_to bought_user_path(current_user.id), class: "myside--top__list__active" do
        %span 購入した商品 過去の取引
        %i.fas.fa-chevron-right
      = link_to news_user_path(current_user.id), class: "myside--top__list" do
        %span ニュース一覧
        %i.fas.fa-chevron-right
      = link_to guide_user_path(current_user.id), class: "myside--top__list" do
        %span ガイド
        %i.fas.fa-chevron-right
      = link_to contact_user_path(current_user.id), class: "myside--top__list" do
        %span お問い合わせ
        %i.fas.fa-chevron-right
    %h3.myside--while
      メルペイ
      %li.myside--while__list
        %span 売り上げ・振込申請
        %i.fas.fa-chevron-right
      %li.myside--while__list
        %span ポイント申請
        %i.fas.fa-chevron-right
    %h3.myside--under
      設定
      = link_to profile_user_path(current_user.id), class: "myside--under__list" do
        %span プロフィール
        %i.fas.fa-chevron-right
      = link_to address_edit_user_path(current_user.id), class: "myside--under__list" do
        %span 発送元・お届け先住所変更
        %i.fas.fa-chevron-right
      = link_to payment_user_path(current_user.id), class: "myside--under__list" do
        %span 支払い方法
        %i.fas.fa-chevron-right
      = link_to email_user_path(current_user.id), class: "myside--under__list" do
        %span メール/パスワード
        %i.fas.fa-chevron-right
      = link_to identification_user_path(current_user.id), class: "myside--under__list" do
        %span 本人情報
        %i.fas.fa-chevron-right
      = link_to phone_user_path(current_user.id), class: "myside--under__list" do
        %span 電話番号の確認
        %i.fas.fa-chevron-right
      = link_to logout_user_path(current_user.id), class: "myside--under__list" do
        %span ログアウト
        %i.fas.fa-chevron-right
  .my--purchase
    %h4.my--purchase__head
      購入した商品
    .my--purchase__situation
      = link_to buying_user_path(current_user.id), class: "non-active" do
        %h5
          取引中
      .active
        %h5
          過去の取引
    .my--purchase--under
      .my--purchase--under--box
        - if @good
          - @good.each do |good|
            = render "toppage/good", { good: good } 
        - else
          取引中の商品がありません


= render 'toppage/footer'

app/views/users/buying.html.haml
= render 'toppage/header'
= render "toppage/button"
= render "user_pankz"

.user-main
  .myside
    %nav.myside--top
      = link_to user_path(current_user.id), class: "myside--top__list" do
        %span マイページ
        %i.fas.fa-chevron-right
      = link_to notification_user_path(current_user.id), class: "myside--top__list" do
        %span お知らせ
        %i.fas.fa-chevron-right
      = link_to todo_user_path(current_user.id), class: "myside--top__list" do
        %span やることリスト
        %i.fas.fa-chevron-right
      = link_to likes_user_path(current_user.id), class: "myside--top__list" do
        %span いいね！一覧
        %i.fas.fa-chevron-right
      = link_to new_good_path, class: 'myside--top__list' do
        %span 出品する
        %i.fas.fa-chevron-right
      = link_to items_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 出品中
        %i.fas.fa-chevron-right
      = link_to dealing_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 取引中
        %i.fas.fa-chevron-right
      = link_to sold_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 売却済み
        %i.fas.fa-chevron-right
      = link_to buying_user_path(current_user.id), class: "myside--top__list__active" do
        %span 購入した商品 取引中
        %i.fas.fa-chevron-right
      = link_to bought_user_path(current_user.id), class: "myside--top__list" do
        %span 購入した商品 過去の取引
        %i.fas.fa-chevron-right
      = link_to news_user_path(current_user.id), class: "myside--top__list" do
        %span ニュース一覧
        %i.fas.fa-chevron-right
      = link_to guide_user_path(current_user.id), class: "myside--top__list" do
        %span ガイド
        %i.fas.fa-chevron-right
      = link_to contact_user_path(current_user.id), class: "myside--top__list" do
        %span お問い合わせ
        %i.fas.fa-chevron-right
    %h3.myside--while
      メルペイ
      %li.myside--while__list
        %span 売り上げ・振込申請
        %i.fas.fa-chevron-right
      %li.myside--while__list
        %span ポイント申請
        %i.fas.fa-chevron-right
    %h3.myside--under
      設定
      = link_to profile_user_path(current_user.id), class: "myside--under__list" do
        %span プロフィール
        %i.fas.fa-chevron-right
      = link_to address_edit_user_path(current_user.id), class: "myside--under__list" do
        %span 発送元・お届け先住所変更
        %i.fas.fa-chevron-right
      = link_to payment_user_path(current_user.id), class: "myside--under__list" do
        %span 支払い方法
        %i.fas.fa-chevron-right
      = link_to email_user_path(current_user.id), class: "myside--under__list" do
        %span メール/パスワード
        %i.fas.fa-chevron-right
      = link_to identification_user_path(current_user.id), class: "myside--under__list" do
        %span 本人情報
        %i.fas.fa-chevron-right
      = link_to phone_user_path(current_user.id), class: "myside--under__list" do
        %span 電話番号の確認
        %i.fas.fa-chevron-right
      = link_to logout_user_path(current_user.id), class: "myside--under__list" do
        %span ログアウト
        %i.fas.fa-chevron-right
  .my--purchase
    .my--purchase__head
      購入した商品
    .my--purchase__situation
      .active
        %h5
          取引中
      = link_to bought_user_path(current_user.id), class: "non-active" do
        %h5
          過去の取引
    .my--purchase--under
      .my--purchase--under--box
        - if @good
          - @good.each do |good|
            = render "toppage/good", { good: good } 
        - else
          取引中の商品がありません
          
= render 'toppage/footer'

app/views/users/dealing.html.haml
= render 'toppage/header'
= render "toppage/button"
= render "user_pankz"


.user-main
  .myside
    %nav.myside--top
      = link_to user_path(current_user.id), class: "myside--top__list" do
        %span マイページ
        %i.fas.fa-chevron-right
      = link_to notification_user_path(current_user.id), class: "myside--top__list" do
        %span お知らせ
        %i.fas.fa-chevron-right
      = link_to todo_user_path(current_user.id), class: "myside--top__list" do
        %span やることリスト
        %i.fas.fa-chevron-right
      = link_to likes_user_path(current_user.id), class: "myside--top__list" do
        %span いいね！一覧
        %i.fas.fa-chevron-right
      = link_to new_good_path, class: 'myside--top__list' do
        %span 出品する
        %i.fas.fa-chevron-right
      = link_to items_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 出品中
        %i.fas.fa-chevron-right
      = link_to dealing_user_path(current_user.id), class: "myside--top__list__active" do
        %span 出品した商品 取引中
        %i.fas.fa-chevron-right
      = link_to sold_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 売却済み
        %i.fas.fa-chevron-right
      = link_to buying_user_path(current_user.id), class: "myside--top__list" do
        %span 購入した商品 取引中
        %i.fas.fa-chevron-right
      = link_to bought_user_path(current_user.id), class: "myside--top__list" do
        %span 購入した商品 過去の取引
        %i.fas.fa-chevron-right
      = link_to news_user_path(current_user.id), class: "myside--top__list" do
        %span ニュース一覧
        %i.fas.fa-chevron-right
      = link_to guide_user_path(current_user.id), class: "myside--top__list" do
        %span ガイド
        %i.fas.fa-chevron-right
      = link_to contact_user_path(current_user.id), class: "myside--top__list" do
        %span お問い合わせ
        %i.fas.fa-chevron-right
    %h3.myside--while
      メルペイ
      %li.myside--while__list
        %span 売り上げ・振込申請
        %i.fas.fa-chevron-right
      %li.myside--while__list
        %span ポイント申請
        %i.fas.fa-chevron-right
    %h3.myside--under
      設定
      = link_to profile_user_path(current_user.id), class: "myside--under__list" do
        %span プロフィール
        %i.fas.fa-chevron-right
      = link_to address_edit_user_path(current_user.id), class: "myside--under__list" do
        %span 発送元・お届け先住所変更
        %i.fas.fa-chevron-right
      = link_to payment_user_path(current_user.id), class: "myside--under__list" do
        %span 支払い方法
        %i.fas.fa-chevron-right
      = link_to email_user_path(current_user.id), class: "myside--under__list" do
        %span メール/パスワード
        %i.fas.fa-chevron-right
      = link_to identification_user_path(current_user.id), class: "myside--under__list" do
        %span 本人情報
        %i.fas.fa-chevron-right
      = link_to phone_user_path(current_user.id), class: "myside--under__list" do
        %span 電話番号の確認
        %i.fas.fa-chevron-right
      = link_to logout_user_path(current_user.id), class: "myside--under__list" do
        %span ログアウト
        %i.fas.fa-chevron-right
  .user-main__sell
    .user-main__sell__head
      出品した商品
    .user-main__sell__body
      = link_to items_user_path(current_user.id), class: "body-tab" do
        出品中
      .active-tab
        取引中
      = link_to sold_user_path(current_user.id), class: "body-tab" do
        売却済み
    .user-main__sell__items
      .user-main__sell__items__box
        - if @goods
          - @goods.each do |good|
            - if good.buy
              = render "good", { good: good }
            - else
        - else
          取引中の商品はありません

= render 'toppage/footer'

app/views/users/email.html.haml
= render 'toppage/header'
= render "toppage/button"
= render "user_pankz"


.user-main
  .myside
    %nav.myside--top
      = link_to user_path(current_user.id), class: "myside--top__list" do
        %span マイページ
        %i.fas.fa-chevron-right
      = link_to notification_user_path(current_user.id), class: "myside--top__list" do
        %span お知らせ
        %i.fas.fa-chevron-right
      = link_to todo_user_path(current_user.id), class: "myside--top__list" do
        %span やることリスト
        %i.fas.fa-chevron-right
      = link_to likes_user_path(current_user.id), class: "myside--top__list" do
        %span いいね！一覧
        %i.fas.fa-chevron-right
      = link_to new_good_path, class: 'myside--top__list' do
        %span 出品する
        %i.fas.fa-chevron-right
      = link_to items_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 出品中
        %i.fas.fa-chevron-right
      = link_to dealing_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 取引中
        %i.fas.fa-chevron-right
      = link_to sold_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 売却済み
        %i.fas.fa-chevron-right
      = link_to buying_user_path(current_user.id), class: "myside--top__list" do
        %span 購入した商品 取引中
        %i.fas.fa-chevron-right
      = link_to bought_user_path(current_user.id), class: "myside--top__list" do
        %span 購入した商品 過去の取引
        %i.fas.fa-chevron-right
      = link_to news_user_path(current_user.id), class: "myside--top__list" do
        %span ニュース一覧
        %i.fas.fa-chevron-right
      = link_to guide_user_path(current_user.id), class: "myside--top__list" do
        %span ガイド
        %i.fas.fa-chevron-right
      = link_to contact_user_path(current_user.id), class: "myside--top__list" do
        %span お問い合わせ
        %i.fas.fa-chevron-right
    %h3.myside--while
      メルペイ
      %li.myside--while__list
        %span 売り上げ・振込申請
        %i.fas.fa-chevron-right
      %li.myside--while__list
        %span ポイント申請
        %i.fas.fa-chevron-right
    %h3.myside--under
      設定
      = link_to profile_user_path(current_user.id), class: "myside--under__list" do
        %span プロフィール
        %i.fas.fa-chevron-right
      = link_to address_edit_user_path(current_user.id), class: "myside--under__list" do
        %span 発送元・お届け先住所変更
        %i.fas.fa-chevron-right
      = link_to payment_user_path(current_user.id), class: "myside--under__list" do
        %span 支払い方法
        %i.fas.fa-chevron-right
      = link_to email_user_path(current_user.id), class: "myside--under__list__active" do
        %span メール/パスワード
        %i.fas.fa-chevron-right
      = link_to identification_user_path(current_user.id), class: "myside--under__list" do
        %span 本人情報
        %i.fas.fa-chevron-right
      = link_to phone_user_path(current_user.id), class: "myside--under__list" do
        %span 電話番号の確認
        %i.fas.fa-chevron-right
      = link_to logout_user_path(current_user.id), class: "myside--under__list" do
        %span ログアウト
        %i.fas.fa-chevron-right
  .page-pass
    .page-pass__box
      %h2 メール/パスワード
    .page-pass__form__contents
      .form-group
        %label メールアドレス
        %input.input-default{:name => "e-mail", :placeholder => "PC・携帯どちらでも可", :type => "e-mail", :value => ""}/
        %p メールアドレスを変更すると確認メールが送信されます。メール内のURLをクリックすると変更完了です。
      .form-group
        %label 現在のパスワード
        %input.input-default{:name => "current-password", :placeholder => "", :type => "password", :value => ""}/        
      .form-group
        %label 新しいパスワード
        %input.input-default{:name => "password", :placeholder => "7文字以上の半角英数字", :type => "password", :value => ""}/
        %p※ 英字と数字の両方を含めて設定してください
      .form-group
        %label 新しいパスワード確認
        %input.input-default{:name => "password-confirmation", :placeholder => "新しいパスワードを再入力", :type => "password", :value => ""}/ 
        %button.btn-red{:type => "submit"} 変更する


= render 'toppage/footer'

app/views/users/profile.html.haml
= render 'toppage/header'
= render "toppage/button"
= render "user_pankz"


.user-main
  .myside
    %nav.myside--top
      = link_to user_path(current_user.id), class: "myside--top__list" do
        %span マイページ
        %i.fas.fa-chevron-right
      = link_to notification_user_path(current_user.id), class: "myside--top__list" do
        %span お知らせ
        %i.fas.fa-chevron-right
      = link_to todo_user_path(current_user.id), class: "myside--top__list" do
        %span やることリスト
        %i.fas.fa-chevron-right
      = link_to likes_user_path(current_user.id), class: "myside--top__list" do
        %span いいね！一覧
        %i.fas.fa-chevron-right
      = link_to new_good_path, class: 'myside--top__list' do
        %span 出品する
        %i.fas.fa-chevron-right
      = link_to items_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 出品中
        %i.fas.fa-chevron-right
      = link_to dealing_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 取引中
        %i.fas.fa-chevron-right
      = link_to sold_user_path(current_user.id), class: "myside--top__list" do
        %span 出品した商品 売却済み
        %i.fas.fa-chevron-right
      = link_to buying_user_path(current_user.id), class: "myside--top__list" do
        %span 購入した商品 取引中
        %i.fas.fa-chevron-right
      = link_to bought_user_path(current_user.id), class: "myside--top__list" do
        %span 購入した商品 過去の取引
        %i.fas.fa-chevron-right
      = link_to news_user_path(current_user.id), class: "myside--top__list" do
        %span ニュース一覧
        %i.fas.fa-chevron-right
      = link_to guide_user_path(current_user.id), class: "myside--top__list" do
        %span ガイド
        %i.fas.fa-chevron-right
      = link_to contact_user_path(current_user.id), class: "myside--top__list" do
        %span お問い合わせ
        %i.fas.fa-chevron-right
    %h3.myside--while
      メルペイ
      %li.myside--while__list
        %span 売り上げ・振込申請
        %i.fas.fa-chevron-right
      %li.myside--while__list
        %span ポイント申請
        %i.fas.fa-chevron-right
    %h3.myside--under
      設定
      = link_to profile_user_path(current_user.id), class: "myside--under__list__active" do
        %span プロフィール
        %i.fas.fa-chevron-right
      = link_to address_edit_user_path(current_user.id), class: "myside--under__list" do
        %span 発送元・お届け先住所変更
        %i.fas.fa-chevron-right
      = link_to payment_user_path(current_user.id), class: "myside--under__list" do
        %span 支払い方法
        %i.fas.fa-chevron-right
      = link_to email_user_path(current_user.id), class: "myside--under__list" do
        %span メール/パスワード
        %i.fas.fa-chevron-right
      = link_to identification_user_path(current_user.id), class: "myside--under__list" do
        %span 本人情報
        %i.fas.fa-chevron-right
      = link_to phone_user_path(current_user.id), class: "myside--under__list" do
        %span 電話番号の確認
        %i.fas.fa-chevron-right
      = link_to logout_user_path(current_user.id), class: "myside--under__list" do
        %span ログアウト
        %i.fas.fa-chevron-right
  .mypage__content
    .mypage__content__head
      %h2.mypage__content__head__text プロフィール
    .mypage__content__image
    = image_tag "haikei.jpg", alt: 'mypageback', height: '156', width: '700', class: 'mypage__content__image'
    .mypage__content__body
      %img{:src => "//static.mercdn.net/images/member_photo_noimage_thumb.png", :width => "60"}
      = form_for @user, url: profile_update_user_path, method: :patch do |f|
        = f.text_field :nick_name, placeholder:"例)AYA☆セール中", class:"nickname-input"
        .mypage__content__body__text
          = f.text_area :profile, placeholder:"例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", class:"mypage-textarea"
          = f.submit "変更する", class:"btn-red"

= render 'toppage/footer'