config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppage#index"
  resources :toppage do
    collection do
      get "search"
    end
  end

  resources :brands
  resources :users, except: :show do 
    member do
      get 'profile'
      patch 'profile_update'
      get 'address_edit'
      patch 'address_update'
      get 'payment'
      get 'email'
      get 'identification'
      get 'phone'
    end
  end

  resources :users, only: :show do
    member do
      get 'logout'
      get 'notification'
      get 'news'
      get 'guide'
      get 'contact'
      get 'todo'
      get 'likes'
      get 'items'
      get 'dealing'
      get 'sold'
      get 'buying'
      get 'bought'
      get 'rates'
    end
  end
  resources :brands
  resources :categories, only: [:index, :show]
  resources :goods,  except: [:index] do
    resources :buys,  only: [:index, :create]
    member do
      get 'selledit'
    end
  end

  resources :credit, only: [:new, :show] do
    collection do
      post 'show', to: 'credits#show'
      post 'pay', to: 'credits#pay'
      post 'delete', to: 'credits#delete'
    end
  end
  
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      get 'done'
    end
  end
end

app/controllers/toppage_controller.rb
class ToppageController < ApplicationController
  def index
    @ladies = Category.find(1)
    @ladies_goods = @ladies.goods.order("created_at DESC").first(10)
    @mens = Category.find(2)
    @mens_goods = @mens.goods.order("created_at DESC").first(10)
    @electronics = Category.find(8)
    @electronics_goods = @electronics.goods.order("created_at DESC").first(10)
    @hobbies = Category.find(6)
    @hobbies_goods = @hobbies.goods.order("created_at DESC").first(10)
    @chanel = Brand.find(1)
    @chanel_goods = @chanel.goods.order("created_at DESC").first(10)
    @louis = Brand.find(3)
    @louis_goods = @louis.goods.order("created_at DESC").first(10)
    @nike = Brand.find(2)
    @nike_goods = @nike.goods.order("created_at DESC").first(10)
    @supreme = Brand.find(4)
    @supreme_goods = @supreme.goods.order("created_at DESC").first(10)

    @children = Category.where( parent_id: params[:parent_id] )
    respond_to do |format|
      format.html
      format.json { render json: @children}
    end
  end

  def search
    @goods = Good.search(params[:keyword])
  end
end

app/views/toppage/_button.html.haml
.post-button
  .btn-post
    = link_to new_good_path, class: "post-btn" do
      = image_tag "Red_Circle_full.png", size: "160x160", alt: "NewPost", class:"post-btn-img"
      .post-btn-text
        %span 出品
      .camera-img
        %svg.img-camera{"aria-hidden" => "true", :height => "54", :viewbox => "0 0 18 16", :width => "60"}
          %path{:d => "M6.3 0L4.653 1.778H1.8c-.99 0-1.8.8-1.8 1.778v10.666C0 15.2.81 16 1.8 16h14.4c.99 0 1.8-.8 1.8-1.778V3.556c0-.978-.81-1.778-1.8-1.778h-2.853L11.7 0H6.3zM9 13.333c-2.484 0-4.5-1.99-4.5-4.444 0-2.453 2.016-4.445 4.5-4.445s4.5 1.992 4.5 4.445c0 2.453-2.016 4.444-4.5 4.444zm0-1.6c1.59 0 2.88-1.273 2.88-2.844S10.59 6.044 9 6.044c-1.59 0-2.88 1.274-2.88 2.845 0 1.57 1.29 2.844 2.88 2.844z", :fill => "currentColor", "fill-rule" => "nonzero"}

app/views/toppage/_footer.html.haml
.image-footer
  .image-footer__container
    .image-footer__container__text
      .text1 スマホで簡単フリマアプリ
      .text2 今すぐ無料ダウンロード
      .image-footer__container__text__link
        = image_tag "footer3.png",class:"icon-img"
        = image_tag "appstore.png",class:"icon-img2"
        = image_tag "google.png",class:"icon-img3"
    .image-footer__container__img
.top-footer
  .top-footer__linkbox
    %ul.top-footer__linkbox__about
      .subject 
        メルカリについて
      %li 会社概要 (運営会社)
      %li 採用情報
      %li プレスリリース
      %li 公式ブログ
      %li メルカリロゴ利用ガイドライン
      .foot-sns
        %a{href: 'https://twitter.com/mercari_jp?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor'}
          = icon'fab','twitter',class:'f-icon'
        %a{href: 'https://ja-jp.facebook.com/mercarijp'}
          = icon'fab','facebook-square',class:'f-icon'
    %ul.top-footer__linkbox__help
      .subject 
        ヘルプ＆ガイド
      %li メルカリガイド
      %li らくらくメルカリ便
      %li ゆうゆうメルカリ便
      %li 大型メルカリ便
      %li 車体取引ガイド
      %li メルカリあんしん・あんぜん宣言！
      %li 偽ブランド品撲滅への取り組み
      %li メルカリボックス
    %ul.top-footer__linkbox__privacy
      .subject 
        プライバシーと利用規約
      %li プライバシーポリシー
      %li メルカリ利用規約
      %li あんしんスマホサポート制度に関する利用規約
      %li コンプライアンスポリシー
    %ul.top-footer__linkbox__privacy2
      %li 個人データの安全管理に係る基本方針
      %li 特定商取引に関する表記
      %li 資金決済法に基づく表示
      %li 法令遵守と犯罪抑止のために
    %ul.top-footer__linkbox__country
      .subject 
        国
      %li 日本
      %li United States
  .top-footer__footer
    %a{href: 'https://www.mercari.com/jp/'}
      = image_tag "footer.png",class:"footer-img"
    .top-footer__footer__text
      © Mercari, Inc.

app/views/toppage/_good-sold.html.haml
= link_to good_path(good.id) do
  .top_ca__ca_block__box__small_box
    .top_ca__ca_block__box__small_box__image
      = image_tag asset_path("redtriangle.png"), size: "80x80", class: "sold-box"
      =image_tag good.images[0].image, size: "188x188", alt: "text", class: "img-box"
      .top_ca__ca_block__box__small_box__price
        %span
          ¥
        = good.price.to_s(:delimited)
    .top_ca__ca_block__box__small_box__message
      = good.name

app/views/toppage/_good.html.haml
= link_to good_path(good.id) do
  .top_ca__ca_block__box__small_box
    .top_ca__ca_block__box__small_box__image
      =image_tag good.images[0].image, size: "188x188", alt: "text", class: "img-box"
      .top_ca__ca_block__box__small_box__price
        %span
          ¥
        = good.price.to_s(:delimited)
    .top_ca__ca_block__box__small_box__message
      = good.name

app/views/toppage/_gooid-sold.html.haml
= link_to good_path(good.id) do
  .top_ca__ca_block__box__small_box
    .top_ca__ca_block__box__small_box__image
      =image_tag good.images[0].image, size: "188x188", alt: "text", class: "img-box"
      .top_ca__ca_block__box__small_box__price
        %span
          ¥
        = good.price.to_s(:delimited)
    .top_ca__ca_block__box__small_box__message
      = good.name

app/views/toppage/_header.html.haml
%header
  .header-inner
    .header-top
      = link_to root_path, class: 'logo' do
        = image_tag "fmarket_logo_red.svg", size: "134x34", alt: "Mercari", class: "logo-img"
      .form
        %form
          %input{placeholder: "何かお探しですか？", class: "text-field", type: "text", size: "100x1"}/
          %button.icon-btn
            %svg.icon-search{"aria-hidden" => "true", :height => "16", :viewbox => "0 0 16 16", :width => "16"}
              %path{d: "M11.435 10.063h-.723l-.256-.247a5.92 5.92 0 0 0 1.437-3.87 5.946 5.946 0 1 0-5.947 5.947 5.92 5.92 0 0 0 3.87-1.437l.247.256v.723L14.637 16 16 14.637l-4.565-4.574zm-5.489 0A4.111 4.111 0 0 1 1.83 5.946 4.111 4.111 0 0 1 5.946 1.83a4.111 4.111 0 0 1 4.117 4.116 4.111 4.111 0 0 1-4.117 4.117z", fill: "currentColor", "fill-rule": "nonzero"}
    .header-nav
      .header-nav-box
        .header-cat-nav
          .header-cat-nav-category
            .header-cat-nav-category--1
              = link_to "レディース", category_path(1), class: "header-cat-nav-category--1--li", value: 1
              = link_to "メンズ", category_path(2), class: "header-cat-nav-category--1--li", value: 2
              = link_to "ベビー・キッズ", category_path(3), class: "header-cat-nav-category--1--li", value: 3
              = link_to "インテリア・住まい・小物", category_path(4), class: "header-cat-nav-category--1--li", value: 4
              = link_to "本・音楽・ゲーム", category_path(5), class: "header-cat-nav-category--1--li", value: 5
              = link_to "おもちゃ・ホビー・グッズ", category_path(6), class: "header-cat-nav-category--1--li", value: 6
              = link_to "コスメ・香水・美容", category_path(7), class: "header-cat-nav-category--1--li", value: 7
              = link_to "家電・スマホ・カメラ", category_path(8), class: "header-cat-nav-category--1--li", value: 8
              = link_to "スポーツ・レジャー", category_path(9), class: "header-cat-nav-category--1--li", value: 9
              = link_to "ハンドメイド", category_path(10), class: "header-cat-nav-category--1--li", value: 10
              = link_to "チケット", category_path(11), class: "header-cat-nav-category--1--li", value: 11
              = link_to "自動車・オートバイ", category_path(12), class: "header-cat-nav-category--1--li", value: 12
              = link_to "その他", category_path(13), class: "header-cat-nav-category--1--li", value: 13
            .header-cat-nav-category--2
            .header-cat-nav-category--3
          %i.header-nav-cat
            = link_to category_path(1), class: 'nav-cat' do
              %svg.icon-cat{"aria-hidden" => "true", :height => "16", :viewbox => "0 0 20 16", :width => "20"}
                %path{:d => "M18.799 15.25h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zm0-6h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zm0-6h-11.5a1.25 1.25 0 1 1 0-2.5h11.5a1.25 1.25 0 0 1 0 2.5zM2 16a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0-6a2 2 0 1 0 0-4 2 2 0 0 0 0 4z", fill: "currentColor", "fill-rule": "nonzero"}
              %span カテゴリーから探す
          %i.header-nav-brand
            = link_to brand_path(1), class: 'nav-brand' do
              %svg.icon-brand{"aria-hidden" => "true", :height => "16", :viewbox => "0 0 23 16", :width => "23"}
                %path{:d => "M6.315 0L4.473 1.806 2.833.019.73 1.977l1.69 1.84L1.198 5.02c-1.594 1.594-1.594 4.188-.01 5.772L6.3 16h13.272a3.08 3.08 0 0 0 3.077-3.077V3.076A3.08 3.08 0 0 0 19.57 0H6.315zm13.46 12.925a.211.211 0 0 1-.205.205H7.504L3.227 8.771a1.226 1.226 0 0 1-.01-1.71L4.38 5.92l1.28 1.371a2.68 2.68 0 1 0 2.13-1.93L6.433 3.907 7.49 2.87h12.082a.211.211 0 0 1 .206.205v9.848h-.002z", fill: "currentColor", "fill-rule": "nonzero"}
              %span ブランドから探す
        .header-login-nav
          -if user_signed_in?
            .header-login-nav__lists
              = link_to likes_user_path(current_user.id), class: "header-login-nav__lists__likes" do
                %i.far.fa-heart
                %span いいね！一覧
              = link_to notification_user_path(current_user.id), class: "header-login-nav__lists__note" do
                %i.far.fa-bell
                %span お知らせ
              = link_to todo_user_path(current_user.id), class: "header-login-nav__lists__todo" do
                %i.fas.fa-check
                %span やることリスト
              = link_to user_path(current_user.id), class:"header-login-nav__lists__mypage" do
                %img{:alt => "", :src => "//static.mercdn.net/images/member_photo_noimage_thumb.png", :width => "32"}/
                %span マイページ
          -else
            = link_to "新規会員登録", step1_signup_index_path, class: 'btn-red'
            = link_to "ログイン", new_user_session_path, class: 'header-login'
         

app/views/toppage/index.html.haml
= render "header"
= render "button"
.toppage
  .fadeSlider
    %span.fadeSlider_01
    %span.fadeSlider_02
    %apan.fadeSlider_03
  .top_popularity_ca
    %h2.top_popularity_ca__title 人気のカテゴリー
    %ul.top_popularity_ca__tags
      %li.top_popularity_ca__tags__tag
        = link_to "レディース", category_path(1)
      %li.top_popularity_ca__tags__tag
        = link_to "メンズ", category_path(2)
      %li.top_popularity_ca__tags__tag
        = link_to "家電・スマホ・カメラ", category_path(3)
      %li.top_popularity_ca__tags__tag
        = link_to "おもちゃ・ホビー・グッズ", category_path(4)
  .top_ca
    .top_ca__ca_block
      .top_ca__ca_block__title
        レディース新着アイテム
        .top_ca__ca_block__name
        .top_ca__ca_block__more_see
          = link_to "もっと見る", category_path(@ladies.id)
          = icon "fas",'chevron-right', class: 'icon'
      .top_ca__ca_block__box
        - @ladies_goods.each do |good|
          -if good.buy
            = render "good-sold", { good: good } 
          - else
            = render "good", { good: good } 

       
  .top_ca
    .top_ca__ca_block
      .top_ca__ca_block__title
        メンズ新着アイテム
        .top_ca__ca_block__name
        .top_ca__ca_block__more_see
          = link_to "もっと見る", category_path(@mens.id)
          = icon "fas",'chevron-right', class: 'icon'
      .top_ca__ca_block__box
        - @mens_goods.each do |good|
          -if good.buy
            = render "good-sold", { good: good } 
          - else
            = render "good", { good: good } 
 
  
  .top_ca
    .top_ca__ca_block
      .top_ca__ca_block__title
        家電・スマホ・カメラ新着アイテム
        .top_ca__ca_block__name
        .top_ca__ca_block__more_see
          = link_to "もっと見る ", category_path(@electronics.id)
          = icon "fas",'chevron-right', class: 'icon'
      .top_ca__ca_block__box
        - @electronics_goods.each do |good|
          -if good.buy
            = render "good-sold", { good: good } 
          - else
            = render "good", { good: good } 

  
  .top_ca
    .top_ca__ca_block
      .top_ca__ca_block__title
        おもちゃ・ホビー・グッズ新着アイテム
        .top_ca__ca_block__name
        .top_ca__ca_block__more_see
          = link_to "もっと見る", category_path(@hobbies.id)
          = icon "fas",'chevron-right', class: 'icon'
      .top_ca__ca_block__box
        - @hobbies_goods.each do |good|
          = render "good", { good: good }

  .top_popularity_ca
    %h2.top_popularity_ca__title 人気のブランド
    %ul.top_popularity_ca__tags
      %li.top_popularity_ca__tags__tag
        = link_to "シャネル", brand_path(1)
      %li.top_popularity_ca__tags__tag
        = link_to "ルイヴィトン", brand_path(3)
      %li.top_popularity_ca__tags__tag
        = link_to "シュプリーム", brand_path(4)
      %li.top_popularity_ca__tags__tag
        = link_to "ナイキ", brand_path(2)
  .top_ca
    .top_ca__ca_block
      .top_ca__ca_block__title
        シャネル新着アイテム
        .top_ca__ca_block__name
        .top_ca__ca_block__more_see
          = link_to "もっと見る", brand_path(@chanel.id)
          = icon "fas",'chevron-right', class: 'icon'
      .top_ca__ca_block__box
        - @chanel_goods.each do |good|
          -if good.buy
            = render "good-sold", { good: good } 
          - else
            = render "good", { good: good } 

  .top_ca
    .top_ca__ca_block
      .top_ca__ca_block__title
        ルイヴィトン新着アイテム
        .top_ca__ca_block__name
        .top_ca__ca_block__more_see
          = link_to "もっと見る", brand_path(@louis.id)
          = icon "fas",'chevron-right', class: 'icon'
      .top_ca__ca_block__box
        - @louis_goods.each do |good|
          -if good.buy
            = render "good-sold", { good: good } 
          - else
            = render "good", { good: good } 

  .top_ca
    .top_ca__ca_block
      .top_ca__ca_block__title
        シュプリーム新着アイテム
        .top_ca__ca_block__name
        .top_ca__ca_block__more_see
          = link_to "もっと見る", brand_path(@supreme.id)
          = icon "fas",'chevron-right', class: 'icon'
      .top_ca__ca_block__box
        - @supreme_goods.each do |good|
          -if good.buy
            = render "good-sold", { good: good } 
          - else
            = render "good", { good: good } 

  .top_ca
    .top_ca__ca_block
      .top_ca__ca_block__title
        ナイキ新着アイテム
        .top_ca__ca_block__name
        .top_ca__ca_block__more_see
          = link_to "もっと見る", brand_path(@nike.id)
          = icon "fas",'chevron-right', class: 'icon'
      .top_ca__ca_block__box
        - @nike_goods.each do |good|
          -if good.buy
            = render "good-sold", { good: good } 
          - else
            = render "good", { good: good } 

= render "footer"
      
      

app/views/toppage/search.html.haml
-@goods.each do |good|
  = good.explain