config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "toppage#index"
  resources :toppage do
    collection do
      get "search"
    end
  end

  resources :brands
  resources :users, except: :show do 
    member do
      get 'profile'
      patch 'profile_update'
      get 'address_edit'
      patch 'address_update'
      get 'payment'
      get 'email'
      get 'identification'
      get 'phone'
    end
  end

  resources :users, only: :show do
    member do
      get 'logout'
      get 'notification'
      get 'news'
      get 'guide'
      get 'contact'
      get 'todo'
      get 'likes'
      get 'items'
      get 'dealing'
      get 'sold'
      get 'buying'
      get 'bought'
      get 'rates'
    end
  end
  resources :brands
  resources :categories, only: [:index, :show]
  resources :goods,  except: [:index] do
    resources :buys,  only: [:index, :create]
    member do
      get 'selledit'
    end
  end

  resources :credit, only: [:new, :show] do
    collection do
      post 'show', to: 'credits#show'
      post 'pay', to: 'credits#pay'
      post 'delete', to: 'credits#delete'
    end
  end
  
  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      get 'step4'
      get 'done'
    end
  end
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :buy, optional: true
  belongs_to :brand, optional: true
  belongs_to :area
  has_many :category_goods
  has_many :categories, through: :category_goods, dependent: :destroy
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  
  def self.search(keyword)
    Good.where('name LIKE(?)', "%#{keyword}%")
  end

end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :move_to_sign_up, except: :show
  def show
    @good = Good.find(params[:id])
    @user_goods = @good.user.goods.first(6)
    if @good.categories.length == 3
      @category = @good.categories[2]
      @category_goods = @good.categories[2].goods.first(6)
    else
      @category = @good.categories[1]
      @category_goods = @good.categories[1].goods.first(6)
    end
    
  end
  
  def new
    @good = Good.new
    @good.images.build
    @good.category_goods.build
  end

  def create
    if params[:images][:image]
      @good = Good.create(good_params)
    else
      redirect_to :back
    end
    if @good.save
      params[:images][:image].each do |image|
        Image.create(image: image, good_id: @good.id )
      end
      params[:category_ids][:category_id].each do |category_id|
        CategoryGood.create(category_id: category_id, good_id: @good.id)
      end
      redirect_to root_path
    end
    
  end

  def destroy
    @good = Good.find(params[:id])
    @good.destroy
    redirect_to user_path(current_user.id)
  end

  def edit
    @good = Good.find(params[:id])
    gon.good = @good
    gon.good_images = @good.images
  end




  def selledit
    @good = Good.find(params[:id])
    
  end


  def update
    @good = Good.find(params[:id])
    @good.update(good_params)
    if @good.update(good_params)
      params[:images][:image].each do |image|
        if image.present?
          Image.create(image: image, good_id: @good.id)  
        end
      end

      params[:destroy][:ids].each do |id|
        if id.present?
          image = Image.find(id) 
          image.destroy 
        end
      end
      
      categories = CategoryGood.where( good_id: @good.id)
      categories.each do |category|
        category.destroy
      end
      params[:category_ids][:category_id].each do |category_id|
        CategoryGood.create(category_id: category_id, good_id: @good.id)
      end
    end
    redirect_to root_path
  end


  private

  def good_params
    params.require(:good).permit(:name, :explain, :size, :price, :method, :ship, :burden, 
      :status, :brand_id, :area_id, :user_id, category_ids: [])
  end

  def move_to_sign_up
    redirect_to new_user_session_path unless user_signed_in?
  end
  
end

app/views/goods/_good.edit.html.haml
.show
  .item-box
    .item-box__name
      = @good.name
    .item-box__word
    - if user_signed_in?
    - else
      .item-box__word__box
        #{@good.name}は、###回の取引実績を持つ
        #{link_to @good.user.nick_name, root_path, class: 'word-link'}
        さんから出品されました。
        #{link_to @good.brand.name, root_path, class: 'word-link'}（
        - category_link = @good.categories[2].name + '/' + @good.categories[0].name
        = link_to category_link, category_path(@good.categories[2].id), class: 'word-link'
        ）の商品で、
        #{@good.area.name}
        から
        #{@good.ship}
        で発送されます。
    .item-box__detail
      .item-box__detail__img
        = image_tag @good.images[0].image, class: 'item-box__detail__img__top'
        .small-images
          - @good.images.each do |image|
            = image_tag image.image, class: 'small-images__img'
      %table
        %tbody
          %tr
            %th
              出品者
            %td
              = link_to @good.user.nick_name, root_path
              %br
              ☺︎4541  ☻50  ☹6
          %tr
            %th
              カテゴリー
            %td
              = link_to @good.categories[0].name, category_path(@good.categories[0].id)
              %br
              %i.fas.fa-chevron-right
                = link_to @good.categories[1].name, category_path(@good.categories[1].id)
              %br
              %i.fas.fa-chevron-right
                = link_to @good.categories[2].name, category_path(@good.categories[2].id)
          %tr
            %th
              ブランド
            %td
              = link_to @good.brand.name, brand_path(@good.id)
          %tr
          - if @good.size.present?
            %th
              商品のサイズ
            %td
              = @good.size
          %tr
            %th
              商品の状態
            %td
              = @good.status
          %tr
            %th
              配送料の負担
            %td
              = @good.burden
          %tr
            %th
              配送の方法
            %td
              = @good.method
          %tr
            %th
              配送元地域
            %td
              = link_to @good.area.name, root_path
          %tr
            %th
              発送日の目安
            %td
              #{@good.ship}で発送
    .item-box__price
      ¥
      .item-box__price__main
        = @good.price.to_s(:delimited)
      .item-box__price__tax
        (税込) 送料込み
    = link_to '購入画面に進む', good_buys_path(@good.id), class: 'item-box__buy'
    .item-box__caution
      この商品はゆうゆうメルカリ便を利用しているため、アプリからのみ購入できます。
    .item-box__description
      = simple_format @good.explain 
  .item--edit__box
    .item--edit__box__top
      = link_to '商品の編集', good_selledit_path(@good.id)
    .item--edit__box__or
      or
    .item--edit__box__stop
      出品を一旦停止する
    .item--edit__box__delete
      この商品を削除する


  
  .comment-box
    .comment-box__content
      .comment-box__content__caution
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .comment-box__content__textarea
      .comment-box__content__btn
        コメントする

app/views/goods/_good_edit.html.haml
.show
  .item-box
    .item-box__name
      = @good.name
    .item-box__word
    - if user_signed_in?
    - else
      .item-box__word__box
        #{@good.name}は、###回の取引実績を持つ
        #{link_to @good.user.nick_name, root_path, class: 'word-link'}
        さんから出品されました。
        #{link_to @good.brand.name, root_path, class: 'word-link'}（
        - category_link = good.categories[2].name + '/' + good.categories[0].name
        = link_to category_link, category_path(good.categories[2].id), class: 'word-link'
        ）の商品で、
        #{@good.area.name}
        から
        #{@good.ship}
        で発送されます。
    .item-box__detail
      .item-box__detail__img
        .big-images
          - @good.images.each do |image|
            = image_tag image.image, size: "300x300", class: 'item-box__detail__img__top'
        .small-images
          - @good.images.each do |image|
            = image_tag image.image,  size: "60x60", class: 'small-images__img'
      %table
        %tbody
          %tr
            %th
              出品者
            %td
              = link_to good.user.nick_name, root_path
              %br
              ☺︎4541  ☻50  ☹6
          %tr
            %th
              カテゴリー
            %td
              = link_to good.categories[0].name, category_path(good.categories[0].id)
              %br
              %i.fas.fa-chevron-right
                = link_to good.categories[1].name, category_path(good.categories[1].id)
              %br
              %i.fas.fa-chevron-right
                = link_to good.categories[2].name, category_path(good.categories[2].id)
          %tr
            %th
              ブランド
            %td
              -if good.brand.nil?
                なし
              -else
                = link_to good.brand.name, brand_path(good.id)
          %tr
          - if good.size.present?
            %th
              商品のサイズ
            %td
              = good.size
          %tr
            %th
              商品の状態
            %td
              = good.status
          %tr
            %th
              配送料の負担
            %td
              = good.burden
          %tr
            %th
              配送の方法
            %td
              = good.method
          %tr
            %th
              配送元地域
            %td
              = link_to good.area.name, root_path
          %tr
            %th
              発送日の目安
            %td
              #{good.ship}で発送
    .item-box__price
      ¥
      .item-box__price__main
        = good.price.to_s(:delimited)
      .item-box__price__tax
        (税込) 送料込み
    .item-box__description
      = simple_format good.explain 
  .item--edit__box
    .item--edit__box__top
      = link_to '商品の編集', edit_good_path(good.id), class: 'item--box__edit'
    .item--edit__box__or
      or
    .item--edit__box__stop
      出品を一旦停止する
    .item--edit__box__delete
      = link_to 'この商品を削除する', good_path(good.id), method: :delete, class: 'item--box__edit'


  
  .comment-box
    .comment-box__content
      .comment-box__content__caution
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .comment-box__content__textarea
      .comment-box__content__btn
        コメントする

app/views/goods/_othergood-ca.html.haml
.same-good
  .same-good__img
    = image_tag good.images[0].image, class:"img-6"
  .same-good__text
    .same-good__text__name
      = good.name
    .same-good__text__price
      %span
        ¥
      = good.price.to_s(:delimited)

app/views/goods/_othergood.html.haml
.other-good
  .other-good__img
    = image_tag good.images[0].image, class:"img-6"
  .other-good__text
    .other-good__text__name
      = good.name
    .other-good__text__price
      %span
        ¥
      = good.price.to_s(:delimited)
      

  
      

app/views/goods/edit.html.haml
.single_header
  %h1.single_header__link
    = link_to root_path do
      = image_tag "mercari_logo_horizontal.png",  size: "185x49", alt: "Mercari", class: "single_header__link__img"

.new-box
  .form-main
    .form-main__text
      商品の情報を入力
    = form_for @good do |f|
      .form-main__container
        .form-img-box
          .form-img-box__text
            %h 出品画像
            %h.red 
              必須
          %p 最大10枚までアップロードできます
          .item__img__dropzone.clearfix
            #preview-edit
            -# １〜５枚目プレビュー表示
            .item__img__dropzone__input
              = f.label :image, for: "upload-image" do
                .input_area
                  = f.file_field :image, multiple: true, name: 'images[image][]', id: "upload-image", class: "upload-image", 'data-image': 0
              
          .item__img__dropzone2.clearfix
            #preview2-edit
            -# ６〜１０枚目プレビュー表示
            .item__img__dropzone2__input2
              = f.label :image, for: "upload-image" do
                .input_area
          %input.upload-image{ multiple: true, type: "hidden", name: "images[image][]"}/
          %input.hidden{ multiple: true, type: "number", name: "destroy[ids][]"}/
        .sell-box
          .sell-box__text1
            %h 商品名
            %h.red 
              必須
          = f.text_field :name,placeholder:"商品名 (必須40文字まで）",class:"good-name"
          .sell-box__text2
            %h 商品の説明
            %h.red
              必須
          = f.text_area :explain,placeholder:"商品の説明 (必須1,000文字以内)  (色、素材、重さ、定価、注意点など）例) 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。",class:"good-explain"
        .sell-box
          .sell-container
            %h 商品の詳細
            .select-details
              .select-details__text
                %h カテゴリー
                %h.red
                  必須
                .select-details__text
                  .category--js.zero
                    = f.collection_select :category_ids, Category.where(" id < ?", 14 ), :id, :name, { prompt: '---' }, { name: 'category_ids[category_id][]'}
                  .category--js.one
                    = f.collection_select :category_ids, Category.where("parent_id > ? and parent_id < ? ", 0, 14 ), :id, :name, { prompt: '---' }, { name: 'category_ids[category_id][]'}
                  .category--js.two
                    = f.collection_select :category_ids, Category.where("parent_id > ?", 13), :id, :name, { prompt: '---' }, { name: 'category_ids[category_id][]'}
              .select-details__text
                %h サイズ
                %h.red
                  必須
              .select-form
                = f.select :size, [["XXS以下", "XXS以下"],["XS(SS)", "XS(SS)"],["S", "S"],["M", "M"],["L", "L"],["XL(LL)", "XL(LL)"],["2XL(3L)", "2XL(3L)"],["3XL(4L)", "3XL(4L)"],["4XL(5L)以上", "4XL(5L以上)"],["FREE SIZE", "FREE SIZE)"]],{ prompt: '---' }
              .select-details__text
                %h ブランド
                %h.gray
                  任意
              .select-form
                = f.collection_select :brand_id, Brand.all, :id, :name, { prompt: '---' }
              .select-details__text
                %h 商品の状態
                %h.red
                  必須
              .select-form
                = f.select :status,[["新品、 未使用","新品、 未使用"],["未使用に近い","未使用に近い"], ["目立った傷や汚れなし","目立った傷や汚れなし"], ["やや傷や汚れあり","やや傷や汚れあり"], ["傷や汚れあり","傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"]],{ prompt: '---' }
        .sell-box
          .sell-container
            %h 配送について
            .select-details
              .select-details__text
                %h 配送料の負担
                %h.red
                  必須
              .select-form
                = f.select :burden, [["送料込み(出品者負担)","送料込み(出品者負担)"],["着払い(購入者負担)","着払い(購入者負担)"]],{ prompt: '---' },id:'burden'
              .method-select.hidden
                .select-details__text
                  %h 配送の方法
                  %h.red
                    必須
                .select-form
                  = f.select :method, [["未定","未定"],["らくらくメルカリ便","らくらくメルカリ便"],["ゆうメール","ゆうメール"],["レターパック","レターパック"],["普通郵便(定形、定形外)","普通郵便(定形、定形外)"],["クロネコヤマト","クロネコヤマト"],["ゆうパック","ゆうパック"],["クリックポスト","クリックポスト"],["ゆうパケット","ゆうパケット"]],{ prompt: '---' }
              .select-details__text
                %h 発送元の地域
                %h.red
                  必須
              .select-form
                = f.collection_select :area_id, Area.all, :id, :name, { prompt: '---' }
              .select-details__text
                %h 発送までの日数
                %h.red
                  必須
              .select-form
                = f.select :ship, [["1〜２日で発送","1〜２日で発送"],["２〜３日で発送","２〜３日で発送"], ["４〜７日で発送","４〜7日で発送"]],{ prompt: '---' }
        .sell-box
          .sell-container
            %h 販売価格(300~9,999,999)
            .select-details
              .price-form
                .price-form__text
                  %h 価格
                  %h.red
                    必須
                .price-form__yen
                  %label
                    ¥
                  = f.text_field :price, placeholder:"例） 300",class:"price-input"
              .buyfee
                販売手数料(10%)
                %h1.buyfee--hyphen -
              .buyfee--profit
                販売利益
                %h1.buyfee--profit__hyphen -
        .sell-box
          .sell-box__text5
            禁止されている出品、行為を必ずご確認ください。
            %br
            またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
            %br
            また、出品をもちまして加盟店規約に同意したことになります。
          = f.hidden_field :user_id, value: current_user.id
          = f.submit "変更する" ,class: "good-edit-btn"
          = link_to root_path do
            .back-btn
              キャンセル
.footer-new
  .footer-text
    %ul
      %li 
        プライバシーポリシー
      %li 
        メルカリ利用規約
      %li 
        特定商取引に関する規約   
  .footer-rogo
    = image_tag "show.png",  size: "80x65"
  .footer-lnc
    ©︎Mercari,lnc.

app/views/goods/new.html.haml
.single_header
  %h1.single_header__link
    = link_to root_path do
      = image_tag "fmarket_logo_red.svg",  size: "185x49", alt: "Mercari", class: "single_header__link__img"

.new-box
  .form-main
    .form-main__text
      商品の情報を入力
    = form_for @good do |f|
      .form-main__container
        .form-img-box
          .form-img-box__text
            %h 出品画像
            %h.red 
              必須
          %p 最大10枚までアップロードできます
          = f.fields_for :images do |image|
            .dropzone-container
              #preview
              .dropzone-area
                = image.label :image, class: "dropzone-box", for: "upload-image" do
                  .input_area
                    = image.file_field :image, multiple: true, name: 'images[image][]', id: "upload-image", class: "upload-image", 'data-image': 0
                    %p ここをクリックしてください
            .dropzone-container2
              #preview2
              .dropzone-area2
                = image.label :image, class: "dropzone-box", for: "upload-image" do
                  .input_area
                    %p ここをクリックしてください

        .sell-box
          .sell-box__text1
            %h 商品名
            %h.red 
              必須
          = f.text_field :name,placeholder:"商品名 (必須40文字まで）",class:"good-name"
          .sell-box__text2
            %h 商品の説明
            %h.red
              必須
          = f.text_area :explain,placeholder:"商品の説明 (必須1,000文字以内)  (色、素材、重さ、定価、注意点など）例) 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。",class:"good-explain"
        .sell-box
          .sell-container
            %h 商品の詳細
            .select-details
              .select-details__text
                %h カテゴリー
                %h.red
                  必須
                .select-details__text
                  .category--js.zero
                    = f.collection_select :category_ids, Category.where(" id < ?", 14 ), :id, :name, { prompt: '---' }, { name: 'category_ids[category_id][]'}
                  .category--js.one
                    = f.collection_select :category_ids, Category.where("parent_id > ? and parent_id < ? ", 0, 14 ), :id, :name, { prompt: '---' }, { name: 'category_ids[category_id][]'}
                  .category--js.two
                    = f.collection_select :category_ids, Category.where("parent_id > ?", 13), :id, :name, { prompt: '---' }, { name: 'category_ids[category_id][]'}
              .select-details__text
                %h サイズ
                %h.red
                  必須
              .select-form
                = f.select :size, [["XXS以下", "XXS以下"],["XS(SS)", "XS(SS)"],["S", "S"],["M", "M"],["L", "L"],["XL(LL)", "XL(LL)"],["2XL(3L)", "2XL(3L)"],["3XL(4L)", "3XL(4L)"],["4XL(5L)以上", "4XL(5L以上)"],["FREE SIZE", "FREE SIZE)"]],{ prompt: '---' }
              .select-details__text
                %h ブランド
                %h.gray
                  任意
              .select-form
                = f.collection_select :brand_id, Brand.all, :id, :name, { prompt: '---' }
              .select-details__text
                %h 商品の状態
                %h.red
                  必須
              .select-form
                = f.select :status,[["新品、 未使用","新品、 未使用"],["未使用に近い","未使用に近い"], ["目立った傷や汚れなし","目立った傷や汚れなし"], ["やや傷や汚れあり","やや傷や汚れあり"], ["傷や汚れあり","傷や汚れあり"], ["全体的に状態が悪い", "全体的に状態が悪い"]],{ prompt: '---' }
        .sell-box
          .sell-container
            %h 配送について
            .select-details
              .select-details__text
                %h 配送料の負担
                %h.red
                  必須
              .select-form
                = f.select :burden, [["送料込み(出品者負担)","送料込み(出品者負担)"],["着払い(購入者負担)","着払い(購入者負担)"]],{ prompt: '---' },id:'burden'
              .method-select.hidden
                .select-details__text
                  %h 配送の方法
                  %h.red
                    必須
                .select-form
                  = f.select :method, [["未定","未定"],["らくらくメルカリ便","らくらくメルカリ便"],["ゆうメール","ゆうメール"],["レターパック","レターパック"],["普通郵便(定形、定形外)","普通郵便(定形、定形外)"],["クロネコヤマト","クロネコヤマト"],["ゆうパック","ゆうパック"],["クリックポスト","クリックポスト"],["ゆうパケット","ゆうパケット"]],{ prompt: '---' }
              .select-details__text
                %h 発送元の地域
                %h.red
                  必須
              .select-form
                = f.collection_select :area_id, Area.all, :id, :name, { prompt: '---' }
              .select-details__text
                %h 発送までの日数
                %h.red
                  必須
              .select-form
                = f.select :ship, [["1〜２日で発送","1〜２日で発送"],["２〜３日で発送","２〜３日で発送"], ["４〜７日で発送","４〜7日で発送"]],{ prompt: '---' }
        .sell-box
          .sell-container
            %h 販売価格(300~9,999,999)
            .select-details
              .price-form
                .price-form__text
                  %h 価格
                  %h.red
                    必須
                .price-form__yen
                  %label
                    ¥
                  = f.text_field :price, placeholder:"例） 300",class:"price-input"
              .buyfee
                販売手数料(10%)
                %h1.buyfee--hyphen -
              .buyfee--profit
                販売利益
                %h1.buyfee--profit__hyphen -
        .sell-box
          .sell-box__text5
            禁止されている出品、行為を必ずご確認ください。
            %br
            またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
            %br
            また、出品をもちまして加盟店規約に同意したことになります。
          = f.hidden_field :user_id, value: current_user.id
          = f.submit "出品する" ,class: "syuppin-btn"
          = link_to root_path do
            .back-btn
              もどる
.footer-new
  .footer-text
    %ul
      %li 
        プライバシーポリシー
      %li 
        メルカリ利用規約
      %li 
        特定商取引に関する規約   
  .footer-rogo
    = image_tag "show.png",  size: "80x65"
  .footer-lnc
    ©︎Mercari,lnc.
              
       

app/views/goods/selledit.html.haml
= render "toppage/header"
.bigbox
  .bigbox--edit
    = render "good_edit", { good: @good }
= render 'toppage/footer.html.haml'
              
       

app/views/goods/show.html.haml
= render "toppage/header"
.show
  .item-box
    .item-box__name
      = @good.name
    .item-box__word
    - if user_signed_in?
      -if @good.buy
        .item-box__word__box
          ※ この商品はすでに購入されております ※
    - else
      .item-box__word__box-1
        #{@good.name}は、###回の取引実績を持つ
        #{link_to @good.user.nick_name, root_path, class: 'word-link'}
        さんから出品されました。
        #{link_to @good.brand.name, root_path, class: 'word-link'}（
        - category_link = @good.categories[2].name + '/' + @good.categories[0].name
        = link_to category_link, category_path(@good.categories[2].id), class: 'word-link'
        ）の商品で、
        #{@good.area.name}
        から
        #{@good.ship}
        で発送されます。
    .item-box__detail
      .item-box__detail__img
        .big-images
          - @good.images.each do |image|
            = image_tag image.image, size: "300x300", class: 'item-box__detail__img__top'
        .small-images
          - @good.images.each do |image|
            = image_tag image.image,  size: "60x60", class: 'small-images__img'
      %table
        %tbody
          %tr
            %th
              出品者
            %td
              = link_to @good.user.nick_name, user_path(params[:id])
              %br
              ☺︎4541  ☻50  ☹6
          %tr
            %th
              カテゴリー
            %td
              = link_to @good.categories[0].name, category_path(@good.categories[0].id)
              %br
              %i.fas.fa-chevron-right
                = link_to @good.categories[1].name, category_path(@good.categories[1].id)
              %br
              %i.fas.fa-chevron-right
                = link_to @good.categories[2].name, category_path(@good.categories[2].id)
          %tr
            %th
              ブランド
            %td
              -unless @good.brand.nil?
                = link_to @good.brand.name, brand_path(@good.id)
              -else 
                なし
          %tr
          - if @good.size.present?
            %th
              商品のサイズ
            %td
              = @good.size
          %tr
            %th
              商品の状態
            %td
              = @good.status
          %tr
            %th
              配送料の負担
            %td
              = @good.burden
          %tr
            %th
              配送の方法
            %td
              = @good.method
          %tr
            %th
              配送元地域
            %td
              = link_to @good.area.name, root_path
          %tr
            %th
              発送日の目安
            %td
              #{@good.ship}で発送
    .item-box__price
      ¥
      .item-box__price__main
        = @good.price.to_s(:delimited)
      .item-box__price__tax
        (税込) 送料込み
    -if @good.buy
      %p.item-box__buy 購入済みの商品
    -else
      = link_to '購入画面に進む', good_buys_path(@good.id), class: 'item-box__buy'
    .item-box__caution
      この商品はゆうゆうメルカリ便を利用しているため、アプリからのみ購入できます。
    .item-box__description
      = simple_format @good.explain   
    .item-box__footer
      .item-box__footer__left
        .item-box__footer__left__good
          ♡ いいね！4 
        .item-box__footer__left__bad
          🏳不適切な商品の報告
      .item-box__footer__right
        🔒あんしん・あんぜんへの取り組み
  .comment-box
    .comment-box__content
      .comment-box__content__caution
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .comment-box__content__textarea
      .comment-box__content__btn
        コメントする
  .link-box
    .link-box__left
      新品■XS■マルジェラ 17aw■4連リング■銀製■シルバー■7257
    .link-box__right
      ソフトケースタイプ・肌色入り サクラクーピーペンシル 12色
  .sns-box
    .none
    .sns-box__container
      %a{href: 'https://ja-jp.facebook.com/mercarijp/'}
        = icon'fab','facebook-square',class:'icon f'
      %a{href: 'https://twitter.com/mercari_jp?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor'}
        = icon'fab','twitter-square',class:'icon t'
      %a{href: 'http://line.me/'}
        = icon'fab','line',class:'icon l'
      %a{href: 'https://www.pinterest.jp/'}
        = icon'fab','pinterest-square',class:'icon p'
  .items-box
    .items-box__other
      .items-box__other__text
        #{@good.user.nick_name}さんのその他の出品
      .items-box__other__img
        -@user_goods.each do |good|
          = render 'othergood', { good: good }

    .items-box__same
      .items-box__same__text
        #{@category.name} その他の商品
      .items-box__same__img
        -@category_goods.each do |good|
          = render 'othergood-ca', { good: good }

  .item-name
    %ul.item-name__text
      %li
        メルカリ >
      %li
        FTC☆オンブレチェックシャツ☆オンブレシャツ☆チェックシャツ☆ボタンシャツ☆
  = render 'toppage/footer.html.haml'